name: Test workflow
on:
  push:
jobs:
  testflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Release
        uses: bohocode/github-actions-maven-release@master
        with:
          gpg-enabled: "true"
          gpg-key-id: ${{ secrets.GITHUB_GPG_KEY_ID }}
          gpg-key: ${{ secrets.GITHUB_GPG_KEY }}

          maven-local-repo-path: /github/workspace/.m2/repository

          maven-args: "-Dmaven.javadoc.skip=true -DskipTests -Ddockerfile.skip -DskipITs -DdockerCompose.skip"
          maven-repo-server-id: bintray-openbankingtoolkit-OpenBankingToolkit
          maven-repo-server-username: openbankingtoolkit
          maven-repo-server-password: ${{ secrets.BINTRAY_API_KEY }}

          git-release-bot-name: "fropenbanking"
          git-release-bot-email: "obst@forgerock.com"

          access-token: ${{ secrets.ACCESS_TOKEN }}

      - name: Dump contents of maven repo
        run: ls -al $GITHUB_WORKSPACE/.m2/repository